# Config file for automatic testing at travis-ci.org
dist: trusty

language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
#  - "pypy"

# Enable newer 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  allow_failures:
    - python: "3.4"
    - python: "3.5"
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - sudo apt-get install gcc-4.7 g++-4.7 python-numpy libicu-dev
  - pip install -r dev-requirements.txt
  - pip install polyglot

# command to run tests, e.g. python setup.py test
script: py.test
